version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Analogy.LogViewer.Interfaces
    versions:
    - 2.10.0
    - 2.10.2
    - 2.11.0
    - 2.12.1
  - dependency-name: Analogy.LogViewer.JsonParser
    versions:
    - 0.4.2
    - 0.4.2.1
    - 0.4.3
  - dependency-name: Analogy.LogViewer.Log4Net
    versions:
    - 1.5.1
    - 1.5.1.1
    - 1.5.2
  - dependency-name: Analogy.LogViewer.Serilog
    versions:
    - 2.2.2.1
    - 2.2.2.2
    - 2.3.0
    - 2.3.1
    - 2.3.2
  - dependency-name: Analogy.LogViewer.XMLParser
    versions:
    - 0.4.1
    - 0.4.1.1
    - 0.4.2
  - dependency-name: Analogy.LogViewer.IISLogsProvider
    versions:
    - 1.5.2
    - 1.5.2.1
    - 1.5.2.2
  - dependency-name: Analogy.LogViewer.gRPC
    versions:
    - 1.5.4.3
    - 1.5.4.4
    - 1.6.0
    - 1.6.1
    - 1.6.3
  - dependency-name: Analogy.LogViewer.Template
    versions:
    - 1.8.1.1
    - 1.8.1.3
    - 1.8.3.1
  - dependency-name: Analogy.LogViewer.PlainTextParser
    versions:
    - 1.4.6.1
    - 1.4.6.2
    - 1.4.8
